package storage

import (
	"time"
)

var SitesRequest = map[string]int{
	"/search": 0,
	"/max":    0,
	"/min":    0,
}

var SitesStorage = map[string]time.Duration{
	"google.com":          0,
	"youtube.com":         0,
	"facebook.com":        0,
	"baidu.com":           0,
	"netflix.com":         0,
	"wikipedia.org":       0,
	"qq.com":              0,
	"taobao.com":          0,
	"yahoo.com":           0,
	"tmall.com":           0,
	"amazon.com":          0,
	"google.co.in":        0,
	"twitter.com":         0,
	"sohu.com":            0,
	"jd.com":              0,
	"live.com":            0,
	"instagram.com":       0,
	"sina.com.cn":         0,
	"weibo.com":           0,
	"google.co.jp":        0,
	"reddit.com":          0,
	"vk.com":              0,
	"360.cn":              0,
	"login.tmall.com":     0,
	"blogspot.com":        0,
	"yandex.ru":           0,
	"google.com.hk":       0,
	"linkedin.com":        0,
	"pornhub.com":         0,
	"google.com.br":       0,
	"twitch.tv":           0,
	"pages.tmall.com":     0,
	"csdn.net":            0,
	"yahoo.co.jp":         0,
	"mail.ru":             0,
	"aliexpress.com":      0,
	"alipay.com":          0,
	"office.com":          0,
	"google.fr":           0,
	"google.ru":           0,
	"google.co.uk":        0,
	"microsoftonline.com": 0,
	"google.de":           0,
	"ebay.com":            0,
	"microsoft.com":       0,
	"livejasmin.com":      0,
	"t.co":                0,
	"bing.com":            0,
	"xvideos.com":         0,
	"google.ca":           0,
}
